tasks:
  - command: |
      poetry install
      poetry run task manage sync-db
      poetry run task app
  
image:
  file: docker/Dockerfile
  
ports:
  - port: 8888
    visibility: private
    onOpen: open-preview