version: "3"

services:
  app:
    container_name: fastapi-gino-arq-uvicorn-2
    image: fastapi-gino-arq-uvicorn
    environment:
      - REDIS_IP=cache
      - REDIS_PORT=6379
      - DB_HOST=database
      - DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - database

  database:
    image: "postgres:latest"
    restart: always
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
