name: Tests

on:
    push:
    pull_request:
      types: [opened, synchronize]

jobs:  
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.3
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install poetry
      shell: bash
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        echo "::set-env name=PATH::$HOME/.poetry/bin:$PATH"

    - name: Configure poetry
      shell: bash
      run: poetry config virtualenvs.in-project true

    - name: Set up cache
      uses: actions/cache@v2
      id: cache
      with:
        path: .venv
        key: venv-${{ hashFiles('**/poetry.lock') }}

    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv

    - name: Upgrade pip
      shell: bash
      run: poetry run python -m pip install pip -U

    - name: Install dependencies
      shell: bash
      run: poetry install

    - name: cache pre-commit
      uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ matrix.python }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install run pre-commit
      run: |
       poetry run pre-commit install
       poetry run pre-commit run --all-files

    - name: Lint
      run: |
        ./scripts/lint.sh > lint-results.txt

    - name: Upload lint results
      uses: actions/upload-artifact@v2
      with:
        name: lint-results
        path: lint-results.txt

    - name: Run tests
      env:
        DB_NAME_TEST: asyncfast_test
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: localhost
      run: |
        poetry run task test
      
    - name: Upload test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-artifacts
        path: .artifacts/*.xml
